BEGIN;

CREATE TABLE public.locks
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY,
    task_key            integer NOT NULL,
    task_query_id       bigint NOT NULL,
    task_source_addr    varchar(600) COLLATE pg_catalog."default",
    marketing_addr      varchar(600) COLLATE pg_catalog."default" NOT NULL,
    structure_number    smallint NOT NULL,
    place_profile_addr  varchar(600) COLLATE pg_catalog."default" NOT NULL,
    place_number        bigint NOT NULL,
    place_profile_login varchar(50) COLLATE pg_catalog."default" NOT NULL,
    profile_addr        varchar(600) COLLATE pg_catalog."default" NOT NULL,
    locked_pos          bigint NOT NULL,
    mp                  text COLLATE pg_catalog."default" NOT NULL,
    created_at          bigint NOT NULL,

    CONSTRAINT marketing_locks_pkey
        PRIMARY KEY (id),
    CONSTRAINT marketing_locks_structure_number_check
        CHECK (structure_number BETWEEN 1 AND 255),
    CONSTRAINT marketing_locks_locked_pos_check
        CHECK (locked_pos BETWEEN 1 AND 4294967295),
    CONSTRAINT marketing_locks_place_number_check
        CHECK (place_number BETWEEN 1 AND 4294967295),
    CONSTRAINT marketing_locks_unique
        UNIQUE
        (
            marketing_addr,
            structure_number,
            place_profile_addr,
            place_number,
            profile_addr,
            locked_pos
        )
);

CREATE INDEX idx_locks_profile_created_at
    ON public.locks
        (marketing_addr, structure_number, profile_addr, created_at, id);

GRANT SELECT, INSERT
    ON TABLE public.locks
    TO cs_programs_user;

GRANT USAGE, SELECT
    ON SEQUENCE public.locks_id_seq
    TO cs_programs_user;

COMMIT;
