<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Common\Common.csproj" />
    <ProjectReference Include="..\..\Contracts\Contracts.Application\Contracts.Application.csproj" />
    <ProjectReference Include="..\ReferalProgram.Core\ReferalProgram.Core.csproj" />
    <ProjectReference Include="..\ReferalProgram.Dto\ReferalProgram.Dto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ReferalProgram.Application.Tests" />
  </ItemGroup>

</Project>
