using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using TonSdk.Core;
using TonSdk.Core.Block;
using TonSdk.Core.Boc;
using UI.Core.TonConnectionAggregate;
using UI.Infrastructure.Persistence;
using UI.Infrastructure.Services;
using Xunit;

namespace UI.Infrastructure.Tests;

public sealed class TonConnectionTests
{
    // Fixtures generated by @ton/ton with an all-zero public key; no private keys.
    public static TheoryData<string, string, string> Wallets()
    {
        var data = new TheoryData<string, string, string>();
        using var json = JsonDocument.Parse(File.ReadAllText(
            Path.Combine(AppContext.BaseDirectory, "Fixtures", "wallet-state-init.json")));
        foreach (var wallet in json.RootElement.EnumerateArray())
            data.Add(wallet.GetProperty("version").GetString()!,
                wallet.GetProperty("address").GetString()!,
                wallet.GetProperty("stateInit").GetString()!);
        return data;
    }

    [Theory]
    [MemberData(nameof(Wallets))]
    public void Recognizes_standard_wallet_code_and_address(string expected, string address, string boc)
    {
        var resolver = new WalletContractVersionResolver();
        Assert.True(resolver.TryResolve(address, boc, out var version));
        Assert.Equal(expected, version);
        var addresses = new WalletAddressService();
        Assert.True(addresses.TryNormalize(address, out var normalized));
        Assert.True(resolver.TryResolve(normalized, boc, out version));
        Assert.Equal(expected, version);
    }

    [Fact]
    public void Unknown_valid_contract_is_saved_as_unknown_version()
    {
        var state = new StateInit(new StateInitOptions
        {
            Code = new CellBuilder().StoreUInt(123, 32).Build(),
            Data = new CellBuilder().Build()
        });
        var address = new Address(0, state.Cell.Hash.ToBytes()).ToString(AddressType.Raw);
        Assert.True(new WalletContractVersionResolver().TryResolve(address, state.Cell.ToString(), out var version));
        Assert.Equal("unknown version", version);
    }

    [Fact]
    public void State_init_for_another_address_is_rejected()
    {
        var fixture = Wallets().First();
        var address = new Address(0, new byte[32]).ToString(AddressType.Raw);
        Assert.False(new WalletContractVersionResolver().TryResolve(address, (string)fixture[2], out _));
    }

    [Theory]
    [InlineData("not base64!")]
    [InlineData("AAAA")]
    public void Malformed_state_init_is_rejected(string boc)
    {
        Assert.False(new WalletContractVersionResolver().TryResolve("0:" + new string('0', 64), boc, out _));
    }

    [Fact]
    public void Absent_state_init_has_unknown_version()
    {
        Assert.True(new WalletContractVersionResolver().TryResolve("0:" + new string('0', 64), null, out var version));
        Assert.Equal("unknown version", version);
    }

    [Fact]
    public void Mapping_uses_wallet_address_as_single_record_identity()
    {
        using var context = new DataContext(new DbContextOptionsBuilder<DataContext>()
            .UseNpgsql("Host=localhost;Database=unused").Options);
        var entity = context.Model.FindEntityType(typeof(TonConnection))!;
        Assert.Equal("ton_connections", entity.GetTableName());
        Assert.Equal(nameof(TonConnection.WalletAddr), Assert.Single(entity.FindPrimaryKey()!.Properties).Name);
        var lastConnected = entity.FindProperty(nameof(TonConnection.LastConnectedAtUtc))!;
        Assert.Equal("last_connected_at", lastConnected.GetColumnName());
        Assert.True(lastConnected.IsNullable);
        Assert.Equal(128, entity.FindProperty(nameof(TonConnection.WalletName))!.GetMaxLength());
        Assert.Equal(64, entity.FindProperty(nameof(TonConnection.AppVersion))!.GetMaxLength());
    }
}
