-- Creates the UI profile cache, current wallet display intentions, and
-- append-only history. Run this in the database configured by
-- ConnectionStrings__UI. When that setting is empty, run it in the Programs
-- database because the API falls back to ConnectionStrings__Programs.

BEGIN;

CREATE TABLE public.profiles
(
    address     varchar(600) PRIMARY KEY,
    login       varchar(100) NOT NULL,
    content     jsonb        NOT NULL,
    updated_at  timestamptz  NOT NULL,

    CONSTRAINT profiles_login_unique UNIQUE (login),
    CONSTRAINT profiles_address_not_blank CHECK (BTRIM(address) <> ''),
    CONSTRAINT profiles_login_not_blank CHECK (BTRIM(login) <> '')
);

CREATE TABLE public.wallet_profile_intents
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_addr   varchar(600) NOT NULL,
    profile_addr  varchar(600) NOT NULL,
    mode          varchar(20)  NOT NULL,
    owned         boolean      NOT NULL,
    created_at    timestamptz  NOT NULL,
    updated_at    timestamptz  NOT NULL,

    CONSTRAINT wallet_profile_intents_identity_unique
        UNIQUE (wallet_addr, profile_addr),
    CONSTRAINT wallet_profile_intents_profile_fkey
        FOREIGN KEY (profile_addr)
        REFERENCES public.profiles (address)
        ON DELETE RESTRICT,
    CONSTRAINT wallet_profile_intents_mode_check
        CHECK (mode IN ('owner', 'preview')),
    CONSTRAINT wallet_profile_intents_wallet_not_blank
        CHECK (BTRIM(wallet_addr) <> '')
);

CREATE INDEX idx_wallet_profile_intents_wallet
    ON public.wallet_profile_intents (wallet_addr, id);

CREATE TABLE public.wallet_profile_intent_events
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      uuid         NOT NULL,
    wallet_addr   varchar(600) NOT NULL,
    profile_addr  varchar(600) NOT NULL,
    event_type    varchar(30)  NOT NULL,
    data          jsonb        NOT NULL DEFAULT '{}'::jsonb,
    occurred_at   timestamptz  NOT NULL,

    CONSTRAINT wallet_profile_intent_events_event_id_unique UNIQUE (event_id),
    CONSTRAINT wallet_profile_intent_events_type_check
        CHECK (event_type IN ('added', 'removed', 'ownership_lost', 'ownership_gained')),
    CONSTRAINT wallet_profile_intent_events_wallet_not_blank
        CHECK (BTRIM(wallet_addr) <> ''),
    CONSTRAINT wallet_profile_intent_events_profile_not_blank
        CHECK (BTRIM(profile_addr) <> '')
);

CREATE INDEX idx_wallet_profile_intent_events_wallet_time
    ON public.wallet_profile_intent_events (wallet_addr, occurred_at, id);

CREATE INDEX idx_wallet_profile_intent_events_profile_time
    ON public.wallet_profile_intent_events (profile_addr, occurred_at, id);

DO $$
DECLARE
    v_database_username text := '';
BEGIN
    IF NULLIF(BTRIM(v_database_username), '') IS NULL THEN
        RAISE EXCEPTION 'v_database_username must be filled.';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = v_database_username) THEN
        RAISE EXCEPTION 'Database role % does not exist.', v_database_username;
    END IF;

    EXECUTE format(
        'GRANT SELECT, INSERT, UPDATE ON TABLE public.profiles TO %I',
        v_database_username);
    EXECUTE format(
        'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.wallet_profile_intents TO %I',
        v_database_username);
    EXECUTE format(
        'GRANT SELECT, INSERT ON TABLE public.wallet_profile_intent_events TO %I',
        v_database_username);
    EXECUTE format(
        'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO %I',
        v_database_username);
END $$;

COMMIT;
