namespace ScheduledTasks.Application;

using System.Security.Cryptography;
using System.Text;

public static class DeterministicCorrelationId
{
    // Stable UUID v5 namespace for scheduled-task command correlation IDs.
    // Never change it: retries must reproduce IDs generated by earlier executions.
    private static readonly Guid NamespaceId =
        new("48528283-0f25-5e33-a119-91d3437f9469");

    public static Guid Create(Guid taskId, long executionNumber, int commandSequence)
    {
        if (executionNumber <= 0)
            throw new ArgumentOutOfRangeException(nameof(executionNumber));
        if (commandSequence < 0)
            throw new ArgumentOutOfRangeException(nameof(commandSequence));

        var namespaceBytes = NamespaceId.ToByteArray(bigEndian: true);
        var nameBytes = Encoding.UTF8.GetBytes(
            $"{taskId:N}:{executionNumber}:{commandSequence}");
        var input = new byte[namespaceBytes.Length + nameBytes.Length];
        namespaceBytes.CopyTo(input, 0);
        nameBytes.CopyTo(input, namespaceBytes.Length);

        var hash = SHA1.HashData(input);
        hash[6] = (byte)((hash[6] & 0x0f) | 0x50);
        hash[8] = (byte)((hash[8] & 0x3f) | 0x80);
        return new Guid(hash.AsSpan(0, 16), bigEndian: true);
    }
}
