<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\IntegrationRequests\IntegrationRequests.csproj" />
    <ProjectReference Include="..\..\..\Libs\TonSdk.Core\TonSdk.Core.csproj" />
    <ProjectReference Include="..\ReferalProgram.Application\ReferalProgram.Application.csproj" />
    <ProjectReference Include="..\ReferalProgram.Core\ReferalProgram.Core.csproj" />
    <ProjectReference Include="..\ReferalProgram.Presentation\ReferalProgram.Presentation.csproj" />
    <ProjectReference Include="..\..\ScheduledTasks\ScheduledTasks.Application\ScheduledTasks.Application.csproj" />
  </ItemGroup>

</Project>
